#!/usr/bin/env python
"""Regenerate DIVERGENCE.md, the mechanical view of this fork versus upstream.

Run from the repository root after merging upstream:

    git fetch upstream master
    python tools/fork_divergence.py > DIVERGENCE.md

CHANGELOG-FORK.md is the hand-written account of what the fork changes and
why. This is the other half: what the two trees actually differ by right now,
generated from git so it cannot drift out of date.

The interesting column is "superseded". A fix whose source files no longer
differ from upstream is one upstream has since made itself, independently.
That is a good outcome, not a loss: it means the bug was real and the fork can
stop carrying the patch.
"""
from __future__ import annotations

import subprocess
import sys

UPSTREAM = 'upstream/master'


def git(*args: str) -> str:
    out = subprocess.run(('git',) + args, capture_output=True, text=True)
    if out.returncode:
        sys.exit('git %s failed: %s' % (' '.join(args), out.stderr.strip()))
    return out.stdout.rstrip('\n')


def have_upstream() -> bool:
    return subprocess.run(('git', 'rev-parse', '--verify', '--quiet', UPSTREAM),
                          capture_output=True).returncode == 0


def fork_commits(base: str) -> list[tuple[str, str, list[str]]]:
    """Our non-merge commits since the last shared point, oldest first."""
    shas = git('rev-list', '--no-merges', '--reverse',
               '%s..HEAD' % base).split('\n')
    commits = []
    for sha in filter(None, shas):
        subject = git('log', '-1', '--format=%s', sha)
        files = [f for f in git('show', '--name-only', '--format=', sha).split('\n') if f]
        commits.append((sha[:8], subject, files))
    return commits


def is_source(path: str) -> bool:
    return (path.endswith('.py') and '/tests/' not in path
            and not path.rsplit('/', 1)[-1].startswith('test_'))


def main() -> None:
    if not have_upstream():
        sys.exit('No %s ref. Add the remote and fetch it first:\n'
                 '    git remote add upstream https://github.com/sympy/sympy.git\n'
                 '    git fetch upstream master' % UPSTREAM)

    base = git('merge-base', 'HEAD', UPSTREAM)
    up_tip, up_date = git('log', '-1', '--format=%h|%cs', UPSTREAM).split('|')
    our_tip, our_date = git('log', '-1', '--format=%h|%cs', 'HEAD').split('|')
    behind = git('rev-list', '--count', 'HEAD..' + UPSTREAM)
    commits = fork_commits(base)

    # Which of our commits has upstream since made itself? Compare the source
    # lines a commit added against the lines the fork still adds on top of
    # upstream. A commit none of whose added lines survive in that net diff has
    # nothing left to contribute: upstream now has equivalent code.
    #
    # Comparing against the net diff rather than against the whole upstream
    # file matters. Lines like "set = Interval(0, 1)" or "ndir = arg.dir(x)"
    # occur in upstream for other distributions and other functions, so asking
    # merely whether upstream contains such a line somewhere reports fixes as
    # adopted that plainly are not.
    def added_source_lines(diff: str) -> set[str]:
        return {ln[1:].strip() for ln in diff.split('\n')
                if ln.startswith('+') and not ln.startswith('+++')
                and len(ln[1:].strip()) > 12}

    superseded = []
    for sha, subject, files in commits:
        sources = [f for f in files if is_source(f)]
        if not sources:
            continue
        mine = added_source_lines(git('show', '--format=', '-U0', sha, '--', *sources))
        if not mine:
            continue
        net = added_source_lines(git('diff', '-U0', UPSTREAM, 'HEAD', '--', *sources))
        if not mine & net:
            superseded.append((sha, subject))

    print('# Divergence from upstream SymPy')
    print()
    print('Generated by `tools/fork_divergence.py`; do not edit by hand.')
    print('See [CHANGELOG-FORK.md](CHANGELOG-FORK.md) for what these changes do')
    print('and [FORK.md](FORK.md) for how they were produced.')
    print()
    print('| | |')
    print('|---|---|')
    print('| Upstream `master` | `%s` (%s) |' % (up_tip, up_date))
    print('| This fork | `%s` (%s) |' % (our_tip, our_date))
    print('| Upstream commits not yet merged here | %s |' % behind)
    print('| Fork commits on top of upstream | %d |' % len(commits))
    print()

    print('## Net difference in the source tree')
    print()
    print('What you get by using this fork instead of upstream, as a diff:')
    print()
    print('```')
    stat = git('diff', '--stat', UPSTREAM, 'HEAD')
    print(stat if stat else '(no difference)')
    print('```')
    print()

    print('## Fork commits')
    print()
    for sha, subject, _ in commits:
        print('- `%s` %s' % (sha, subject))
    print()

    if superseded:
        print('## Possibly adopted upstream since')
        print()
        print('None of the source lines these commits added survive in the diff')
        print('the fork still carries, so upstream now has equivalent code and')
        print('the patch can be dropped. Compared line by line rather than by')
        print('meaning, so confirm before dropping one.')
        print()
        for sha, subject in superseded:
            print('- `%s` %s' % (sha, subject))
        print()


if __name__ == '__main__':
    main()
